#!/usr/bin/env perl

my @all = ("Integrate", "png", "jpeg", "tiff", "gif", "xpm", "tga", "bmp", "msp", "xbm");
my @enabled = ();
foreach my $i (@all){
	push(@enabled, $i);
}

open(OUT, ">", "config.mk");

sub dll {
	my $targets = "src/format/$_[0].o $_[1]";

	print OUT ("TARGETS += fmt_$_[0].dll\n");
	print OUT ("fmt_$_[0].dll: $targets\n");
	print OUT ("\t\$(CC) -shared \$(LDFLAGS) -o \$@ $targets\n");
}

sub has_in {
	return grep(/^$_[0]$/, @enabled);
}

sub scan_proj {
	print OUT (uc($_[0]) . "_OBJS =");

	opendir(my $dh, "external/$_[0]/src");
	my @files = readdir($dh);
	foreach my $fn (@files){
		if(($fn eq ".") || ($fn eq "..")){
			next;
		}elsif($fn =~ /\.c$/){
			$fn =~ s/\.c$/.o/;
			print OUT (" external/$_[0]/src/$fn");
		}
	}
	closedir($dh);

	print OUT ("\n");

	print OUT ("CFLAGS += -Iexternal/$_[0]/include\n");

	if(defined($_[1])){
		print OUT ("CFLAGS += -D$_[1]\n");
	}

	if($_[0] eq 'libz'){
		print OUT ("OBJS += external/$_[0].a\n");
	}else{
		if(has_in("Integrate")){
			my $fmt = $_[0];
			$fmt =~ s/^lib//;

			print OUT ("OBJS += src/format/$fmt.o\n");
			print OUT ("OBJS += external/$_[0].a\n");
		}else{
			my $fmt = $_[0];
			my $targets = "";
			$fmt =~ s/^lib//;

			if(($_[0] eq "libpng") or ($_[0] eq "libtiff")){
				$targets = "$targets external/libz.a";
			}

			dll($fmt, "src/genutil.o src/ds.o external/$_[0].a $targets", "");
		}
	}
\
	print OUT ("external/$_[0].a: \$(" . uc($_[0]) . "_OBJS)\n");
	print OUT ("\t\$(AR) rcs \$@ \$(" . uc($_[0]) . "_OBJS)\n");
	print OUT ("\n");
}

foreach my $i (@ARGV){
	my $mode = "add";
	my $do = $i;
	if(substr($i, 0, 1) eq "-"){
		$mode = "del";
		$do = substr($i, 1);
	}elsif(substr($i, 0, 1) eq "+"){
		$do = substr($i, 1);
	}

	my @query = ($do);
	if($do eq "all"){
		@query = ();
		foreach my $e (@all){
			push(@query, $e);
		}
	}

	foreach my $e (@query){
		if($mode eq "add"){
			@enabled = push(@enabled, $e);
		}elsif($mode eq "del"){
			@new = ();
			foreach my $e2 (@enabled) {
				if(!($e2 eq $e)){
					push(@new, $e2);
				}
			}
			@enabled = @new;
		}
	}
}

print("Enabled:");
foreach my $i (@enabled){
	if($i =~ /^[a-z]/){
		print(" $i");
	}
}
print("\n");
if(has_in("Integrate")){
	print("Integrating image formats\n");
}

foreach my $i (@enabled){
	if($i eq "png"){
		scan_proj("libpng", "DOPNG");
	}elsif($i eq "tiff"){
		scan_proj("libtiff", "DOTIFF");
	}elsif($i eq "jpeg"){
		scan_proj("libjpeg", "DOJPEG");
	}elsif($i eq "gif"){
		scan_proj("libgif", "DOGIF");
	}elsif($i eq "Integrate"){
		print OUT ("CFLAGS += -DINTEGRATE\n");
		print OUT ("\n");
	}else{
		print OUT ("CFLAGS += -DDO" . uc($i) . "\n");
		print OUT ("\n");
		if(has_in("Integrate")){
			print OUT ("OBJS += src/format/$i.o\n");
		}else{
			dll($i, "src/genutil.o src/ds.o", "");
		}
	}

}

scan_proj("libz");

close(OUT);
