LIBZ_OBJS = libz/src/adler32.o libz/src/compress.o libz/src/crc32.o libz/src/deflate.o libz/src/gzclose.o libz/src/gzlib.o libz/src/gzread.o libz/src/gzwrite.o libz/src/infback.o libz/src/inffast.o libz/src/inflate.o libz/src/inftrees.o libz/src/trees.o libz/src/uncompr.o libz/src/zutil.o libz/src/gzclose.o libz/src/compress.o libz/src/uncompr.o libz/src/zutil.o libz/src/inffast.o libz/src/gzwrite.o libz/src/gzread.o libz/src/adler32.o libz/src/inftrees.o libz/src/crc32.o libz/src/infback.o libz/src/gzlib.o libz/src/deflate.o libz/src/trees.o libz/src/inflate.o
CFLAGS += -Ilibz/include
OBJS += libz.a
libz.a: $(LIBZ_OBJS)
	$(AR) rcs $@ $(LIBZ_OBJS)

LIBPNG_OBJS = libpng/src/pngrio.o libpng/src/png.o libpng/src/pngerror.o libpng/src/pngget.o libpng/src/pngmem.o libpng/src/pngpread.o libpng/src/pngread.o libpng/src/pngrio.o libpng/src/pngrtran.o libpng/src/pngrutil.o libpng/src/pngset.o libpng/src/pngpread.o libpng/src/pngtrans.o libpng/src/pngwio.o libpng/src/pngwrite.o libpng/src/pngwtran.o libpng/src/pngwutil.o libpng/src/pngerror.o libpng/src/pngmem.o libpng/src/pngget.o libpng/src/png.o libpng/src/pngwio.o libpng/src/pngset.o libpng/src/pngread.o libpng/src/pngtrans.o libpng/src/pngwtran.o libpng/src/pngrutil.o libpng/src/pngwrite.o libpng/src/pngwutil.o libpng/src/pngrtran.o
CFLAGS += -Ilibpng/include
OBJS += libpng.a
libpng.a: $(LIBPNG_OBJS)
	$(AR) rcs $@ $(LIBPNG_OBJS)

LIBJPEG_OBJS = libjpeg/src/cdjpeg.o libjpeg/src/cdjpeg.o libjpeg/src/jcmainct.o libjpeg/src/jcinit.o libjpeg/src/jaricom.o libjpeg/src/jcapistd.o libjpeg/src/jaricom.o libjpeg/src/jcapimin.o libjpeg/src/jcapistd.o libjpeg/src/jcarith.o libjpeg/src/jccoefct.o libjpeg/src/jccolor.o libjpeg/src/jcdctmgr.o libjpeg/src/jchuff.o libjpeg/src/jcinit.o libjpeg/src/jcmainct.o libjpeg/src/jcmarker.o libjpeg/src/jcmaster.o libjpeg/src/jcomapi.o libjpeg/src/jcparam.o libjpeg/src/jcprepct.o libjpeg/src/jcsample.o libjpeg/src/jctrans.o libjpeg/src/rdbmp.o libjpeg/src/jdapimin.o libjpeg/src/jdapistd.o libjpeg/src/jdarith.o libjpeg/src/jdatadst.o libjpeg/src/jdatasrc.o libjpeg/src/jdcoefct.o libjpeg/src/jdcolor.o libjpeg/src/jddctmgr.o libjpeg/src/jdhuff.o libjpeg/src/jdinput.o libjpeg/src/jdmainct.o libjpeg/src/jdmarker.o libjpeg/src/jdmaster.o libjpeg/src/jdmerge.o libjpeg/src/jdpostct.o libjpeg/src/jdsample.o libjpeg/src/jdtrans.o libjpeg/src/jerror.o libjpeg/src/jfdctflt.o libjpeg/src/jfdctfst.o libjpeg/src/jfdctint.o libjpeg/src/jidctflt.o libjpeg/src/jidctfst.o libjpeg/src/jidctint.o libjpeg/src/jmemansi.o libjpeg/src/jcarith.o libjpeg/src/jccoefct.o libjpeg/src/jmemmgr.o libjpeg/src/jcapimin.o libjpeg/src/jmemnobs.o libjpeg/src/jcomapi.o libjpeg/src/jquant1.o libjpeg/src/jquant2.o libjpeg/src/jutils.o libjpeg/src/rdcolmap.o libjpeg/src/rdgif.o libjpeg/src/jcmarker.o libjpeg/src/rdppm.o libjpeg/src/rdrle.o libjpeg/src/rdswitch.o libjpeg/src/rdtarga.o libjpeg/src/transupp.o libjpeg/src/wrbmp.o libjpeg/src/wrgif.o libjpeg/src/jcmaster.o libjpeg/src/wrppm.o libjpeg/src/wrrle.o libjpeg/src/wrtarga.o libjpeg/src/jcdctmgr.o libjpeg/src/jcparam.o libjpeg/src/jccolor.o libjpeg/src/jctrans.o libjpeg/src/jcprepct.o libjpeg/src/jcsample.o libjpeg/src/jdapimin.o libjpeg/src/jdatadst.o libjpeg/src/jdapistd.o libjpeg/src/rdbmp.o libjpeg/src/jdatasrc.o libjpeg/src/jddctmgr.o libjpeg/src/jchuff.o libjpeg/src/jdmainct.o libjpeg/src/jdmaster.o libjpeg/src/jdpostct.o libjpeg/src/jdcoefct.o libjpeg/src/jfdctflt.o libjpeg/src/jdinput.o libjpeg/src/jdarith.o libjpeg/src/jdmerge.o libjpeg/src/jdtrans.o libjpeg/src/jerror.o libjpeg/src/jfdctfst.o libjpeg/src/jmemansi.o libjpeg/src/jmemnobs.o libjpeg/src/jutils.o libjpeg/src/jdcolor.o libjpeg/src/jidctfst.o libjpeg/src/rdrle.o libjpeg/src/jidctflt.o libjpeg/src/rdcolmap.o libjpeg/src/rdppm.o libjpeg/src/jdsample.o libjpeg/src/jquant1.o libjpeg/src/jquant2.o libjpeg/src/jmemmgr.o libjpeg/src/wrppm.o libjpeg/src/wrrle.o libjpeg/src/rdswitch.o libjpeg/src/wrbmp.o libjpeg/src/jdhuff.o libjpeg/src/rdtarga.o libjpeg/src/wrtarga.o libjpeg/src/rdgif.o libjpeg/src/wrgif.o libjpeg/src/jdmarker.o libjpeg/src/jidctint.o libjpeg/src/jfdctint.o libjpeg/src/transupp.o
CFLAGS += -Ilibjpeg/include
OBJS += libjpeg.a
libjpeg.a: $(LIBJPEG_OBJS)
	$(AR) rcs $@ $(LIBJPEG_OBJS)

LIBTIFF_OBJS = libtiff/src/tif_aux.o libtiff/src/tif_aux.o libtiff/src/tif_close.o libtiff/src/tif_codec.o libtiff/src/tif_color.o libtiff/src/tif_compress.o libtiff/src/tif_dir.o libtiff/src/tif_dirinfo.o libtiff/src/tif_dirread.o libtiff/src/tif_dirwrite.o libtiff/src/tif_dumpmode.o libtiff/src/tif_error.o libtiff/src/tif_extension.o libtiff/src/tif_fax3.o libtiff/src/tif_fax3sm.o libtiff/src/tif_flush.o libtiff/src/tif_getimage.o libtiff/src/tif_hash_set.o libtiff/src/tif_jbig.o libtiff/src/tif_jpeg.o libtiff/src/tif_jpeg_12.o libtiff/src/tif_lerc.o libtiff/src/tif_luv.o libtiff/src/tif_lzma.o libtiff/src/tif_lzw.o libtiff/src/tif_next.o libtiff/src/tif_ojpeg.o libtiff/src/tif_open.o libtiff/src/tif_packbits.o libtiff/src/tif_pixarlog.o libtiff/src/tif_predict.o libtiff/src/tif_print.o libtiff/src/tif_read.o libtiff/src/tif_strip.o libtiff/src/tif_swab.o libtiff/src/tif_thunder.o libtiff/src/tif_tile.o libtiff/src/tif_version.o libtiff/src/tif_warning.o libtiff/src/tif_webp.o libtiff/src/tif_win32.o libtiff/src/tif_write.o libtiff/src/tif_zip.o libtiff/src/tif_zstd.o libtiff/src/tif_fax3.o libtiff/src/tif_fax3sm.o libtiff/src/tif_dir.o libtiff/src/tif_close.o libtiff/src/tif_hash_set.o libtiff/src/tif_dumpmode.o libtiff/src/tif_error.o libtiff/src/tif_extension.o libtiff/src/tif_compress.o libtiff/src/tif_codec.o libtiff/src/tif_dirinfo.o libtiff/src/tif_flush.o libtiff/src/tif_jpeg_12.o libtiff/src/tif_jpeg.o libtiff/src/tif_lerc.o libtiff/src/tif_predict.o libtiff/src/tif_color.o libtiff/src/tif_lzma.o libtiff/src/tif_jbig.o libtiff/src/tif_getimage.o libtiff/src/tif_print.o libtiff/src/tif_lzw.o libtiff/src/tif_ojpeg.o libtiff/src/tif_open.o libtiff/src/tif_luv.o libtiff/src/tif_next.o libtiff/src/tif_dirwrite.o libtiff/src/tif_strip.o libtiff/src/tif_pixarlog.o libtiff/src/tif_swab.o libtiff/src/tif_dirread.o libtiff/src/tif_warning.o libtiff/src/tif_read.o libtiff/src/tif_tile.o libtiff/src/tif_packbits.o libtiff/src/tif_win32.o libtiff/src/tif_thunder.o libtiff/src/tif_write.o libtiff/src/tif_webp.o libtiff/src/tif_zip.o libtiff/src/tif_version.o libtiff/src/tif_zstd.o
CFLAGS += -Ilibtiff/include
OBJS += libtiff.a
libtiff.a: $(LIBTIFF_OBJS)
	$(AR) rcs $@ $(LIBTIFF_OBJS)

