[package]
name = "image_rs"
version = "0.1.0"
edition = "2024"

[lib]
path = "./image.rs"
crate-type = ["staticlib"]

[dependencies]
image = { version = "0.25.6", features = ["avif", "bmp", "dds", "exr", "ff", "gif", "hdr", "ico", "pnm", "qoi", "rayon", "tga", "webp"] }
