#ifndef __WVRESOURCE_H__
#define __WVRESOURCE_H__

#define IDM_STATUS (1000)
#define IDM_STATUS_PROGRESS (IDM_STATUS + 1)

#define IDM_LISTBOX (1010)

#define IDM_FILE (1020)
#define IDM_FILE_QUIT (IDM_FILE + 1)

#define IDM_VIEW (1030)
#define IDM_VIEW_REASPECT (IDM_VIEW + 1)
#define IDM_VIEW_10_LARGER (IDM_VIEW + 2)
#define IDM_VIEW_10_SMALLER (IDM_VIEW + 3)

#define IDM_ABOUT (1090)
#define IDM_ABOUT_CREDITS (IDM_ABOUT + 1)
#define IDM_ABOUT_VERSION (IDM_ABOUT + 2)

/* 1100-1199 */
#define IDM_BUTTONS (1100)

#endif
