name: "Build WinView"

on:
  push:

concurrency:
  group: "build"
  cancel-in-progress: true

jobs:
  build-win32:
    name: "Build for Windows 32-bit"
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Watcom
      run: sudo mkdir -p /usr/watcom && curl -L https://github.com/open-watcom/open-watcom-v2/releases/download/Last-CI-build/ow-snapshot.tar.xz | sudo tar xJvf - -C /usr/watcom
    - name: Set variables
      run: |
        echo "WATCOM=/usr/watcom" >> $GITHUB_ENV
        echo "INCLUDE=/usr/watcom/h" >> $GITHUB_ENV
        echo "/usr/watcom/binl64" >> $GITHUB_PATH
    - name: Build
      run: make -j4 OPTMK=watcom
    - name: Rename
      run: mv winview.exe winview32.exe
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: build-win32
        path: winview32.exe

  build-win64:
    name: "Build for Windows 64-bit"
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install packages
      run: sudo apt-get install mingw-w64
    - name: Build
      run: make -j4
    - name: Rename
      run: mv winview.exe winview64.exe
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: build-win64
        path: winview64.exe

  release:
    name: "Release"
    runs-on: ubuntu-latest

    permissions:
      contents: write

    needs: [build-win32, build-win64]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download from build-win32
      uses: actions/download-artifact@v4
      with:
        name: build-win32
    - name: Download from build-win64
      uses: actions/download-artifact@v4
      with:
        name: build-win64
    - name: Delete old release
      run: gh release delete "$(make get-version)" --cleanup-tag -y || true
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Release
      run: gh release create -t "v$(make get-version)" "$(make get-version)" winview*.exe -n "Version \`$(make get-version)\` was built in this release"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

